"""Regenerate site/people.js from the IIS people page (https://iis.ee.ethz.ch/people.html).

The page renders each group's members from a JSON endpoint; this script reads those
endpoints and writes a static list the rental forms use for their name/email picker.
The browser cannot query iis.ee.ethz.ch directly (no CORS), hence the static copy.

    python3 scripts/fetch_people.py

Run it whenever the institute's people list changes (or let the refresh-people
GitHub workflow do it).
"""
import html, json, re, sys, urllib.request
from pathlib import Path

BASE = "https://iis.ee.ethz.ch"
OUT = Path(__file__).resolve().parent.parent / "site" / "people.js"


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "eecis-device-rental/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8")


def main():
    page = get(f"{BASE}/people.html")
    # Each list is preceded by its <h2> heading and carries its own JSON URL.
    blocks = re.findall(r"<h2>(.*?)</h2>.*?data-json-url=\"([^\"]+)\"", page, re.S)
    if not blocks:
        sys.exit("no person lists found on the people page (markup changed?)")

    people, seen = [], set()
    for heading, url in blocks:
        group = html.unescape(re.sub(r"\s+", " ", heading)).strip()
        data = json.loads(get(BASE + url))["data"]
        for p in data:
            a = p["attributes"]
            name, email = a.get("name", "").strip(), a.get("email", "").strip()
            if not name or not email:
                continue
            key = (name.lower(), email.lower())
            if key in seen:
                continue  # professors appear in their own group list as well
            seen.add(key)
            people.append({"name": name, "email": email, "group": group})

    lines = ",\n".join("  " + json.dumps(p, ensure_ascii=False) for p in people)
    OUT.write_text(
        "// Generated by scripts/fetch_people.py from https://iis.ee.ethz.ch/people.html.\n"
        "// Do not edit by hand; rerun the script instead.\n"
        f"export const PEOPLE = [\n{lines},\n];\n",
        encoding="utf-8",
    )
    print(f"wrote {len(people)} people to {OUT}")


if __name__ == "__main__":
    main()
