"""Regenerate the device seed SQL from EECIS_DEVICE_LIST.xlsx.

Writes two things:
  * supabase/migrations/0004_seed_devices.sql  — the labelled devices (rows that carry a
    "Nr.x" in column B). This migration is already applied in production; the script must
    keep producing it byte-identically.
  * the generated block inside supabase/migrations/0006_devices_admin.sql — the devices
    that exist but have no physical label (no "Nr.x"). They are seeded with unit_no = 1
    and labelled = false, and only the region between the BEGIN/END markers is rewritten,
    so the hand-written SQL around it survives.
"""
import openpyxl, re, sys

# Some unlabelled devices' name/maker/model do not fall out cleanly from splitting
# column A on newlines (the sheet packs part number, frequency range, "(Dedicated)"
# etc. into that one cell in an order that does not match our name/maker/model
# columns). For those, override with the owner's preferred values, keyed by the raw
# text of column A exactly as read from the sheet.
OVERRIDES = {
    "Opal Kelly XEM7360-K160T \n(XC7K160T-1, 2-GiB DDR3)":
        ("Opal Kelly XEM7360-K160T", "Opal Kelly", "XEM7360-K160T (XC7K160T-1, 2-GiB DDR3)"),
    "Opal Kelly XEM7360-K410T ":
        ("Opal Kelly XEM7360-K410T", "Opal Kelly", "XEM7360-K410T"),
    "ZHDC-10-63-S+\n50-6000MHz\nDirectional Coupler\n(Dedicated)":
        ("Directional Coupler 50-6000 MHz (Dedicated)", "Mini-Circuits", "ZHDC-10-63-S+"),
    "ZCDC10-02263S+\n2-26.5GHz\nDirectional Coupler\n(Dedicated)":
        ("Directional Coupler 2-26.5 GHz (Dedicated)", "Mini-Circuits", "ZCDC10-02263S+"),
    "ZX47-60LN-S+\n500-8000 MHz LNA\n(Dedicated)":
        ("LNA 500-8000 MHz (Dedicated)", "Mini-Circuits", "ZX47-60LN-S+"),
    "zx60-83LN-S+\n10-8000 MHz Power Detector\n(Dedicated)":
        ("Power Detector 10-8000 MHz (Dedicated)", "Mini-Circuits", "zx60-83LN-S+"),
    "Active Technologies \nAWG-5064":
        ("Arbitrary Waveform Generator", "Active Technologies", "AWG-5064"),
}

wb = openpyxl.load_workbook(sys.argv[1] if len(sys.argv) > 1 else "EECIS_DEVICE_LIST.xlsx", data_only=True)
ws = wb["Device List"]
rows, unlabelled, cur, raw = [], [], None, None
for a, b in ws.iter_rows(min_row=3, values_only=True):
    if a:
        raw = str(a)
        parts = [p.strip() for p in raw.split("\n") if p.strip()]
        cur = (parts + [None, None])[:3]          # name, maker, model
    if b and cur:
        rows.append((*cur, int(re.search(r"\d+", str(b)).group())))
    elif a and cur:
        # A device that exists but carries no "Nr.x" label: a single unlabelled unit.
        unlabelled.append((*OVERRIDES.get(raw, cur), 1))
def q(v): return "null" if v is None else "'" + v.replace("'", "''") + "'"
def values(rs): return ",\n".join(f"  ({q(n)}, {q(m)}, {q(md)}, {u})" for n, m, md, u in rs)

out = ["-- generated by scripts/seed_from_xlsx.py; do not edit by hand",
       "insert into devices(name, maker, model, unit_no) values"]
out.append(values(rows) + "\non conflict do nothing;")
open("supabase/migrations/0004_seed_devices.sql", "w").write("\n".join(out) + "\n")

BEGIN = "-- BEGIN generated by scripts/seed_from_xlsx.py; do not edit by hand"
END = "-- END generated by scripts/seed_from_xlsx.py"
path = "supabase/migrations/0006_devices_admin.sql"
try:
    src = open(path).read()
except FileNotFoundError:
    src = None
if src is None or BEGIN not in src or END not in src:
    print(f"warning: {path} has no generated block; unlabelled devices not written")
else:
    block = (BEGIN + "\ninsert into devices(name, maker, model, unit_no, labelled) values\n"
             + ",\n".join(f"  ({q(n)}, {q(m)}, {q(md)}, {u}, false)" for n, m, md, u in unlabelled)
             + "\non conflict do nothing;\n" + END)
    start, stop = src.index(BEGIN), src.index(END) + len(END)
    open(path, "w").write(src[:start] + block + src[stop:])
print(f"wrote {len(rows)} labelled and {len(unlabelled)} unlabelled devices")
