-- Devices that exist but carry no physical "Nr.x" label.
-- (Later sections of this file add the admin-editable device list and device_status.)

alter table devices add column labelled boolean not null default true;

-- BEGIN generated by scripts/seed_from_xlsx.py; do not edit by hand
insert into devices(name, maker, model, unit_no, labelled) values
  ('Opal Kelly XEM7360-K160T', 'Opal Kelly', 'XEM7360-K160T (XC7K160T-1, 2-GiB DDR3)', 1, false),
  ('Opal Kelly XEM7360-K410T', 'Opal Kelly', 'XEM7360-K410T', 1, false),
  ('Low Distortion Generator', 'Stanford Research', 'DS360', 1, false),
  ('Pure Power', 'RF Power Amplifier', '1040L', 1, false),
  ('High-speed Digital Analyzer', 'LeCroy', 'HDA125', 1, false),
  ('Oscilloscope', 'LeCroy', 'SDA 8330HD', 1, false),
  ('ARM/FPGA SoC Development Board', 'Digilent', 'Zybo Z7 20', 1, false),
  ('Compute Accelerator Card', 'AMD', 'Alveo V80', 1, false),
  ('Arbitrary Waveform Generator', 'Active Technologies', 'AWG-5064', 1, false),
  ('Directional Coupler 50-6000 MHz (Dedicated)', 'Mini-Circuits', 'ZHDC-10-63-S+', 1, false),
  ('Directional Coupler 2-26.5 GHz (Dedicated)', 'Mini-Circuits', 'ZCDC10-02263S+', 1, false),
  ('LNA 500-8000 MHz (Dedicated)', 'Mini-Circuits', 'ZX47-60LN-S+', 1, false),
  ('Power Detector 10-8000 MHz (Dedicated)', 'Mini-Circuits', 'zx60-83LN-S+', 1, false),
  ('Isolation Transformer', 'Eaton', 'IS1000HGDV', 1, false)
on conflict do nothing;
-- END generated by scripts/seed_from_xlsx.py

-- device_availability gains `labelled` so the site can render the name correctly.
drop view if exists public.device_availability;
create view public.device_availability with (security_invoker = false) as
  select d.id as device_id, d.name, d.maker, d.model, d.unit_no, d.labelled,
         coalesce(array_agg(daterange(r.start_date, r.end_date, '[]') order by r.start_date)
                  filter (where r.id is not null), '{}') as busy
    from devices d
    left join rentals r on r.device_id = d.id and r.status = 'approved' and r.end_date >= current_date
   where d.active
   group by d.id;
grant select on public.device_availability to authenticated;

-- ---------------------------------------------------------------------------
-- Admins: a small allow-list table plus the helper the policies and the site use.
-- Add or remove admins by editing this table (Supabase Table Editor -> admins).
-- ---------------------------------------------------------------------------
create table admins (email text primary key);
insert into admins(email) values ('hongse@ethz.ch') on conflict do nothing;
alter table admins enable row level security;
grant select on public.admins to authenticated;
grant all on public.admins to service_role;
-- A signed-in user may look up their own row (that is what "am I an admin?" needs);
-- the rest of the list stays invisible.
create policy admins_own_read on admins for select to authenticated using (email = auth.email());

-- security definer so the device policies can consult the whole table regardless of
-- the caller's own row visibility.
create function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from admins where email = auth.email())
$$;
grant execute on function public.is_admin() to authenticated;

-- devices_read (0003) stays `using (true)` on purpose: an admin has to see inactive
-- devices too, and the site filters on `active` for everyone else.
-- There is deliberately no delete policy and no delete grant: retiring a device means
-- setting active = false, so the rentals that reference it keep their foreign key.
create policy devices_admin_insert on devices for insert to authenticated with check (is_admin());
create policy devices_admin_update on devices for update to authenticated using (is_admin()) with check (is_admin());
grant insert, update on public.devices to authenticated;

-- ---------------------------------------------------------------------------
-- Who currently has (or has asked for) each device.
-- A deliberate decision by the owner: every signed-in ETH user sees the borrower's,
-- their lab manager's and their professor's name and email for current and upcoming
-- rentals, so they know whom to ask about a device. security_invoker = false makes the
-- view read rentals as its owner, past the per-user RLS policy on that table — which is
-- exactly what exposes those rows, so keep the where clause tight.
-- ---------------------------------------------------------------------------
create view public.device_status with (security_invoker = false) as
  select r.device_id, r.id as rental_id, r.status::text as status,
         r.start_date, r.end_date,
         r.borrower_name, r.borrower_email,
         r.manager_name, r.manager_email,
         r.professor_name, r.professor_email
    from rentals r
   where r.status in ('pending', 'approved')
     and r.end_date >= current_date;
grant select on public.device_status to authenticated;
